// <auto-generated />
namespace Awesome_Time.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserTiersAndArticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTiersAndArticles));
        
        string IMigrationMetadata.Id
        {
            get { return "201609170849451_User-Tiers-And-Articles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
